# Generated by Django 5.0.4 on 2025-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=50)),
                ('incorrect_answer1', models.CharField(max_length=50)),
                ('incorrect_answer2', models.CharField(max_length=50)),
                ('incorrect_answer3', models.CharField(max_length=50)),
            ],
        ),
    ]
